server {
    listen 80;
    server_name localhost;

    # 1静态资源映射
    location /video/ {
        #alias /home/cjn/桌面/healthy/api/video/;
	alias C:\Users\17857\AndroidStudioProjects\healthy\api\video\
        add_header Access-Control-Allow-Origin *;
        autoindex off; # 关闭目录浏览
    }

    location / {
        proxy_pass http://127.0.0.1:8080/;
        proxy_set_header Host $host;
    }
}
