server:
  address: 0.0.0.0  # 强制允许外部访问
  port: 8080

# 视频文件配置
video:
  # 视频存放的本地路径（相对路径：相对于项目 api 文件夹）
  local-path: video/
  # 视频访问地址（给前端用的）
  web-url: http://10.0.2.2/video/
  # 封面访问地址
  cover-web-url: http://10.0.2.2/video/covers/

spring:
  profiles:
    active: cjn
  application:
    name: healthy
  datasource:
    url: "jdbc:mysql://${datasource.host:localhost}:${datasource.port:3319}/${datasource.dbname:healthy}?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false"
    username: "${datasource.username:root}"
    password: "${datasource.password:root}"
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: create
    show-sql: true
  # 上传文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: ${file.size:20MB}
      max-request-size: ${file.size:20MB}
qianwen:
  api:
    key: "sk-41cc37e376ce40bb9e07ab265cf6a2bd"

---

spring:
  config:
    activate:
      on-profile: jbz
  application:
    name: healthy
  datasource:
    url: "jdbc:mysql://${datasource.host:localhost}:${datasource.port:3306}/${datasource.dbname:healthy}?useUnicode=true&characterEncoding=utf-8"
    username: "${datasource.username:yunzhi}"
    password: "${datasource.password:yunzhi}"
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: create
    show-sql: true
  # 上传文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: ${file.size:20MB}
      max-request-size: ${file.size:20MB}

---

spring:
  config:
    activate:
      on-profile: hc
  application:
    name: healthy
  datasource:
    url: "jdbc:mysql://${datasource.host:localhost}:${datasource.port:3306}/${datasource.dbname:healthy}?useUnicode=true&characterEncoding=utf-8"
    username: "${datasource.username:root}"
    password: "${datasource.password:180615}"
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: create
    show-sql: true
  # 上传文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: ${file.size:20MB}
      max-request-size: ${file.size:20MB}