version: '3.1'

services:
  mysql:
    image: mariadb:10.2
    hostname: mysql57
    ports:
      - "3319:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthy
    volumes:
      - ./db:/var/lib/mysql
    command: 
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - net

networks:
  net: